Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/my_finetuned_ppocrv4_rec_en/
  save_epoch_step: 5
  eval_batch_step: [0, 500]
  character_dict_path: /home/jupyter/PaddleOCR_Training/ocr_output/custom_char_dict.txt
  max_text_length: 128
  pretrained_model: /home/jupyter/PaddleOCR_Training/pretrained_models/en_PP-OCRv4_rec_train/best_accuracy
  save_inference_dir: ./inference/my_finetuned_ppocrv4_rec_en_infer/
  use_visualdl: false
  seed: 2025

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: CTCHead

Loss:
  name: CTCLoss
  use_focal_loss: false

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /
    label_file_list: ["/home/jupyter/PaddleOCR_Training/ocr_output/rec_gt_train.txt"]
    ratio_list: [1.0]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - SVTRRecResizeImg:
          image_shape: [3, 48, 320]
          padding: True
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'chw'
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /
    label_file_list: ["/home/jupyter/PaddleOCR_Training/ocr_output/rec_gt_eval.txt"]
    ratio_list: [1.0]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - SVTRRecResizeImg:
          image_shape: [3, 48, 320]
          padding: True
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'chw'
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    batch_size_per_card: 64
    drop_last: false
    num_workers: 4